spring:
  application:
    name: L1-sb-unit-integration-tests-controller-advice
  datasource:
    url: jdbc:postgresql://localhost:5432/l1-sb-testing
    username: demo_user
    password: demo_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
