spring:
  application:
    name:
      L1B-spring-boot-spa-mazur
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/my-prod-app-realm

  logging:
    level:
      org:
        springframework:
          security:
            DEBUG