version: '3'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: l1-spring-boot_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    ports:
      - "5433:5432"
