#В цьому файлі нічого змінбвати не потрбіно було
#Все вже було налаштовано
#Повернув все як було
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/employees_db
    url: jdbc:postgresql://localhost:5432/l1b-zalic_303_304_db
    username: demo_user
#    username: postgres
    password: demo_pass
#    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        Цей рядок взагалі не потрібний
#        enable_lazy_load_no_trans: true  # Дозволяє lazy loading поза транзакцією
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
