spring:
  application:
    name: add-user-demo

  security:
    oauth2:
      resourceserver:
        jwt:
          # ???????????? ??? ????????? ??????? (JWT)
          issuer-uri: http://localhost:8081/realms/my-prod-app-realm

keycloak:
  admin-client:
    # ???????????? ??? ????????????????? ??????? ?? Keycloak
    server-url: http://localhost:8081
    realm: my-prod-app-realm
    client-id: backend-admin-client
    client-secret: GSibOYdMsVPCixdA7UAD2ujxBntONZyK
