spring:
  application:
    name: L1-spring-boot-security-spa-klots
  security:
    oauth2:
      resourceserver:
        jwt:
          #????'??????: ???????? ?? ??? ????? realm
          issuer-uri: http://localhost:8081/realms/my-prod-app-realm
