spring:
  application:
    name: l1-spring-security-db

  # PostgreSQL DataSource
  datasource:
    url: jdbc:postgresql://localhost:5433/l1-spring-security_db
    username: demo_user
    password: demo_password
    driver-class-name: org.postgresql.Driver
    # JPA / Hibernate
    # ???????? Spring, ?? ?? ???????? ? PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
        # ???????????, ?? ??????????? ??????? ? Hibernate
    properties:
      hibernate:
        # ???? ????????, ?? ?? ???????? ? ????????? PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false