spring:
  application:
    name: L1-spring-boot-security

  # ?????? ?????? Keycloak ??????? ?? ????? Realm
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/spring-demo-realm
        # ??? ???????? ???????? ??? ????????? ??????, ??? ????????? ??? ?? ????????????????
        # ??????? ??? Client ID ?? Client Secret ? Keycloak
      client:
        registration:
          keycloak:
            client-id: spring-boot-client
            client-secret: IxE1hXYdyAG878VB3avcH64kobhiojj3
        provider:
          keycloak:
            token-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token

