version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: L1-spring-boot-security
      POSTGRES_USER: us
      POSTGRES_PASSWORD: us
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: keycloak/keycloak:24.0.3
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: us
      KEYCLOAK_ADMIN_PASSWORD: us
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: L1-spring-boot-security
      KC_DB_USERNAME: us
      KC_DB_PASSWORD: us
    command: start-dev
    ports:
      - "8180:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
